export const nomesBrasileiros = [
  // Femininos
  "Ana",
  "Beatriz",
  "Carla",
  "Daniela",
  "Eliana",
  "Fernanda",
  "Gabriela",
  "Helena",
  "Isabela",
  "Joana",
  "Katia",
  "Larissa",
  "Mariana",
  "Natalia",
  "Olivia",
  "Patricia",
  "Quiteria",
  "Raquel",
  "Sandra",
  "Tatiana",
  "Ursula",
  "Valeria",
  "Wanda",
  "Xenia",
  "Yasmin",
  "Zuleica",
  "Amanda",
  "Bruna",
  "Camila",
  "Debora",
  "Eduarda",
  "Fabiana",
  "Geovana",
  "Heloisa",
  "Ivana",
  "Janaina",
  "Kelly",
  "Luana",
  "Marcela",
  "Nathalia",
  "Orlanda",
  "Paula",
  "Renata",
  "Sabrina",
  "Tais",
  "Vanessa",
  "Wilma",
  "Yara",
  "Zilda",

  // Masculinos
  "Adriano",
  "Bruno",
  "Carlos",
  "Daniel",
  "Eduardo",
  "Fernando",
  "Gabriel",
  "Henrique",
  "Igor",
  "João",
  "Kaio",
  "Lucas",
  "Marcos",
  "Nicolas",
  "Otavio",
  "Pedro",
  "Quirino",
  "Ricardo",
  "Sandro",
  "Tiago",
  "Ulisses",
  "Vicente",
  "Wagner",
  "Xavier",
  "Yuri",
  "Zeca",
  "Antonio",
  "Bernardo",
  "Claudio",
  "Diego",
  "Erick",
  "Fabio",
  "Gustavo",
  "Heitor",
  "Ivo",
  "Julio",
  "Kevin",
  "Leonardo",
  "Matheus",
  "Nelson",
  "Oscar",
  "Paulo",
  "Rafael",
  "Samuel",
  "Tomás",
  "Vitor",
  "Walter",
  "Yago",
  "Zeno",
];

export const sobrenomesBrasileiros = [
  "Silva",
  "Santos",
  "Oliveira",
  "Souza",
  "Rodrigues",
  "Ferreira",
  "Alves",
  "Pereira",
  "Lima",
  "Gomes",
  "Costa",
  "Ribeiro",
  "Martins",
  "Carvalho",
  "Almeida",
  "Lopes",
  "Soares",
  "Fernandes",
  "Vieira",
  "Barbosa",
  "Rocha",
  "Dias",
  "Nunes",
  "Mendes",
  "Machado",
  "Gonçalves",
  "Araujo",
  "Barros",
  "Freitas",
  "Cardoso",
  "Braga",
  "Borges",
  "Morais",
  "Nascimento",
  "Campos",
  "Moura",
  "Batista",
  "Cavalcanti",
  "Melo",
  "Pinto",
  "Teixeira",
  "Ramos",
  "Santiago",
  "Cunha",
  "Castro",
  "Macedo",
  "Farias",
  "Guimarães",
  "Moreira",
  "Duarte",
  "Dantas",
  "Amaral",
  "Reis",
  "Coelho",
  "Rosa",
  "Peixoto",
  "Figueiredo",
  "Andrade",
  "Carneiro",
  "Franco",
  "Correia",
  "Bezerra",
  "Cruz",
  "Monteiro",
  "Pacheco",
  "Chaves",
  "Leite",
  "Arruda",
  "Furtado",
  "Cordeiro",
  "Esteves",
  "Macedo",
  "Neves",
  "Lacerda",
  "Simões",
  "Queiroz",
  "Moraes",
  "Siqueira",
  "Rezende",
  "Camargo",
  "Tavares",
  "Barreto",
  "Torres",
  "Maia",
  "Medeiros",
  "Miranda",
  "Bittencourt",
  "Sarmento",
  "Santana",
  "Nogueira",
  "Seabra",
  "Sampaio",
  "Assis",
  "Valente",
  "Aguiar",
  "Brito",
  "Pimentel",
  "Serra",
  "Menezes",
  "Viana",
];

export const states = [
  "AC", // Acre
  "AL", // Alagoas
  "AP", // Amapá
  "AM", // Amazonas
  "BA", // Bahia
  "CE", // Ceará
  "DF", // Distrito Federal
  "ES", // Espírito Santo
  "GO", // Goiás
  "MA", // Maranhão
  "MT", // Mato Grosso
  "MS", // Mato Grosso do Sul
  "MG", // Minas Gerais
  "PA", // Pará
  "PB", // Paraíba
  "PR", // Paraná
  "PE", // Pernambuco
  "PI", // Piauí
  "RJ", // Rio de Janeiro
  "RN", // Rio Grande do Norte
  "RS", // Rio Grande do Sul
  "RO", // Rondônia
  "RR", // Roraima
  "SC", // Santa Catarina
  "SP", // São Paulo
  "SE", // Sergipe
  "TO", // Tocantins
];

export const streets = ["Rua", "Avenida", "Travessa", "Praça", "Rodovia"];

export const names = [
  "das Flores",
  "dos Anjos",
  "da Paz",
  "das Palmeiras",
  "do Sol",
  "do Campo",
  "da Alegria",
  "da Liberdade",
  "do Amor",
  "dos Sonhos",
  "das Estrelas",
  "da Harmonia",
  "do Horizonte",
  "da União",
  "da Esperança",
  "da Vitória",
  "da Amizade",
  "da Tranquilidade",
  "das Margaridas",
  "das Rosas",
];

export const cities = [
  "São Paulo",
  "Rio de Janeiro",
  "Belo Horizonte",
  "Porto Alegre",
  "Curitiba",
  "Brasília",
  "Fortaleza",
  "Salvador",
  "Recife",
  "Manaus",
  "Belém",
  "Goiânia",
  "Natal",
  "Teresina",
  "João Pessoa",
  "São Luís",
  "Maceió",
  "Aracaju",
  "Campo Grande",
  "Florianópolis",
  "Vitória",
  "Cuiabá",
  "Boa Vista",
  "Palmas",
  "Macapá",
  "Porto Velho",
  "Rio Branco",
  "Santos",
  "Campinas",
  "Niterói",
];

export const validCEPs = {
  "São Paulo": [
    "01000-000",
    "01001-000",
    "01002-000",
    "01003-000",
    "01004-000",
    // Adicione mais CEPs de São Paulo conforme necessário
  ],
  "Rio de Janeiro": [
    "20000-000",
    "20001-000",
    "20002-000",
    "20003-000",
    "20004-000",
    // Adicione mais CEPs do Rio de Janeiro conforme necessário
  ],
  "Belo Horizonte": [
    "30000-000",
    "30001-000",
    "30002-000",
    "30003-000",
    "30004-000",
    // Adicione mais CEPs de Belo Horizonte conforme necessário
  ],
  // Adicione mais cidades com seus respectivos CEPs válidos
};
